chore: new action to emit notifs

diff --git a/.github/workflows/tst-github-action.yaml b/.github/workflows/tst-github-action.yaml
--- a/.github/workflows/tst-github-action.yaml
+++ b/.github/workflows/tst-github-action.yaml
@@ -9,17 +9,46 @@ env:
   REF: test_secret
   name: TEST_SECRET
   GH_TOKEN: ${{ github.token }}
+  TF_LOG: ERROR
+  TF_LOG_PATH: ./terraform.log
+  TF_VERSION: 1.1.4
 
 jobs:
-  test-decoding-base64:
+  job1:
     runs-on: ubuntu-latest
+    outputs:
+      output1: ${{ steps.error.outputs.status }}
+      jobid: ${{ steps.error.outputs.jobid }}
     steps:
+      - name: Emit Error
+        id: error
+        run: |
+          echo "Error: error sending PUT request to /auth/admin/realms/master/identity-provider/instances/azureidir: 500 Internal Server Error. Response body: {error:unknown_error} Error: error sending PUT request to /auth/admin/realms/standard/identity-provider/instances/githubpublic: 500 Internal Server Error. Response body: {error:unknown_error} Error: error sending PUT request to /auth/admin/realms/github/identity-provider/instances/github/mappers/bb1a8da4-f904-4c8a-8458-95f2c71b7d0e: 500 Internal Server Error. Response body: <html><head><title>Error</title></head><body>Internal Server Error</body></html>"
+          echo "status=failed" >> "$GITHUB_OUTPUT"
+          echo "status=failed" >> "$GITHUB_OUTPUT"
+          exit 1
+  job2:
+    runs-on: ubuntu-latest
+    needs: job1
+    if: ${{needs.job1.outputs.output1}} == 'failed'
+    steps:
+      - name: Pull the main branch again
+        run: |
+          git pull origin dev --rebase
+
+      - name: Setup Terraform
+        id: tf
+        uses: bcgov/sso-requests-actions/actions/setup-terraform@v0.55.0
+        with:
+          context: .
+          apply: false
+        continue-on-error: true
       - name: Fetch Action Logs
         id: summary
         run: |
-          summary=$(gh run view ${{ github.run_id }} --log --repo nithinkuruba/test-gh-actions | awk 'match($0, /gh .*/) {print substr($0, RSTART, RLENGTH)}' | tr '\n' ',' | sed -e 's|["'\'']||g' | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g')
+          summary=$(cat terraform.log | awk 'match($0, /gh .*/) {print substr($0, RSTART, RLENGTH)}' | tr '\n' ',' | sed -e 's|["'\'']||g')
           echo "$summary"
-          echo "summary=$summary" >> $GITHUB_OUTPUT
+          echo "summary=$summary" >> "$GITHUB_OUTPUT"
       - name: Rocket.Chat Notification
         uses: fjogeleit/http-request-action@master
         with:
